<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function tenLastPost(): array
    {
        $qb = $this->createQueryBuilder('p')
                    ->setMaxResults(10)
                    ->orderBy('p.published', 'DESC');
        return $qb->getQuery()->getResult();
    }
}
