<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use AppBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function lastPost(int $page, int $nbPerPage): Paginator
    {
        $qb = $this->createQueryBuilder('p')
                    ->orderBy('p.published', 'DESC')
                    ->getQuery();

        $qb->setFirstResult(($page-1)*$nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($qb, true);
    }

    public function lastPostVisitor(int $limit): Array
    {
        $qb = $this->createQueryBuilder('p')
                    ->orderBy('p.published', 'DESC')
                    ->setMaxResults($limit)
                    ->join('p.user', 'u')
                    ->addSelect('u')
                    ->getQuery();
            

        return $qb->getArrayResult();
    }

    public function isUrlAliasUnique(string $urlAlias)
    {
        $is_unique = $this->findBy(array('urlAlias' => $urlAlias));
        return count($is_unique) === 0;
    }
}
